# Generated by Django 5.2.6 on 2025-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
