# Generated by Django 5.2.6 on 2025-09-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_endereco'),
        ('orders', '0002_pedido_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.endereco'),
        ),
    ]
