# Generated by Django 5.2.6 on 2025-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produto_imagem_principal_imagemproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='products.categoria'),
        ),
    ]
