# Generated by Django 5.2.6 on 2025-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
